import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-r from-gray-700 via-gray-900 to-black">
        <div className="flex items-center justify-center h-screen">
          <div className="container">
            <div className="bg-white rounded-lg shadow-lg p-5 md:p-20 mx-2">
              <div className="text-center">
                <h2 className="text-4xl tracking-tight leading-10 font-extrabold text-gray-900 sm:text-5xl sm:leading-none md:text-6xl">
                  Low Impact<span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-cyan-600"> Living</span>
                </h2>
                <h3 className='text-xl md:text-3xl mt-10'>Coming Soon</h3>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
